# Generated by Django 6.0.1 on 2026-01-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('linearity', 'Linearity'), ('accuracy', 'Accuracy'), ('precision', 'Precision'), ('lod_loq', 'LOD/LOQ')], max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'step')},
            },
        ),
        migrations.CreateModel(
            name='PrecisionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate_values', models.JSONField()),
                ('mean', models.FloatField(null=True)),
                ('rsd', models.FloatField(null=True)),
                ('passed', models.BooleanField(null=True)),
                ('validation_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validation.validationstep')),
            ],
        ),
        migrations.CreateModel(
            name='LODLOQData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_responses', models.JSONField()),
                ('slope', models.FloatField()),
                ('lod', models.FloatField(null=True)),
                ('loq', models.FloatField(null=True)),
                ('passed', models.BooleanField(null=True)),
                ('validation_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validation.validationstep')),
            ],
        ),
        migrations.CreateModel(
            name='LinearityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentrations', models.JSONField()),
                ('responses', models.JSONField()),
                ('slope', models.FloatField(null=True)),
                ('intercept', models.FloatField(null=True)),
                ('r_squared', models.FloatField(null=True)),
                ('passed', models.BooleanField(null=True)),
                ('validation_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validation.validationstep')),
            ],
        ),
        migrations.CreateModel(
            name='AccuracyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('80', '80%'), ('100', '100%'), ('120', '120%')], max_length=10)),
                ('measured_values', models.JSONField()),
                ('recovery', models.FloatField(null=True)),
                ('mean_recovery', models.FloatField(null=True)),
                ('rsd', models.FloatField(null=True)),
                ('passed', models.BooleanField(null=True)),
                ('validation_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validation.validationstep')),
            ],
        ),
    ]
