# Generated by Django 5.2.6 on 2026-02-03 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options'),
        ('validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('correction', 'Request Correction')], max_length=20)),
                ('comments', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_reviews', to='projects.project')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supporting_documents/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('chromatogram', 'Chromatogram'), ('instrument_data', 'Instrument Data'), ('certificate', 'Certificate'), ('sop', 'SOP/Procedure'), ('raw_data', 'Raw Data'), ('other', 'Other')], default='other', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='validation.validationstep')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
