# Generated by Django 6.0.1 on 2026-01-19 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=255)),
                ('method_type', models.CharField(choices=[('assay', 'Assay')], default='assay', max_length=20)),
                ('technique', models.CharField(choices=[('hplc', 'HPLC'), ('uv', 'UV')], max_length=20)),
                ('guideline', models.CharField(choices=[('ich_q2', 'ICH Q2')], default='ich_q2', max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('linearity', 'LINEARITY'), ('accuracy', 'ACCURACY'), ('precision', 'PRECISION'), ('lod_loq', 'LOD/LOQ'), ('review', 'REVIEW'), ('approved', 'APPROVED')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
