# Generated by Django 5.2.6 on 2026-02-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_approved_at_project_qa_approver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
